version: "3.8"

services:
  database:
    image: postgres:17
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - rillastudios_network
    environment:
      POSTGRES_USER: rillstudios
      POSTGRES_DB: rillastudios
      POSTGRES_PASSWORD: ${SOFTWARE_PASSWORD}
  cache:
    image: redis:8.0.2
    restart: always
    networks:
      - rillastudios_network
  directus:
    restart: always
    image: directus/directus:11.9.2
    ports:
      - "8055:8055"
    user: 0:0
    networks:
      - rillastudios_network
    depends_on:
      - cache
      - database
    environment:
        KEY: ${SOFTWARE_PASSWORD}
        SECRET: ${SOFTWARE_PASSWORD}
        PUBLIC_URL: http://localhost:8055
        DB_CLIENT: "pg"
        DB_HOST: "database"
        DB_PORT: "5432"
        DB_DATABASE: "rillastudios"
        DB_USER: "rillstudios"
        DB_PASSWORD: ${SOFTWARE_PASSWORD}
        EMAIL_FROM: ${EMAIL_FROM}
        EMAIL_TRANSPORT: "smtp"
        EMAIL_SMTP_HOST: ${SMTP_HOST}
        EMAIL_SMTP_PORT: 25
        EMAIL_SMTP_SECURE: "false"
        EMAIL_SMTP_IGNORE_TLS: "false"
        CACHE_ENABLED: "true"
        CACHE_STORE: "redis"
        CACHE_REDIS: "redis://cache:6379"
        REDIS: "redis://cache:6379"
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        CACHE_AUTO_PURGE: "true"
networks:
  rillastudios_network:

